
export const FETCH_SUBSCRIBERS_LIST = "subscribers/FETCH_SUBSCRIBERS_LIST";
export const FETCH_SUBSCRIBERS_LIST_SUCCESS = "subscribers/FETCH_SUBSCRIBERS_LIST_SUCCESS";
export const FETCH_SUBSCRIBERS_LIST_FAILURE = "subscribers/FETCH_SUBSCRIBERS_LIST_FAILURE";
export const SET_SELECTED_SUBSCRIBER = "subscribers/SET_SELECTED_SUBSCRIBER";