
export const FETCH_SUBSCRIBERS_LIST = "subscriberes/FETCH_SUBSCRIBERS_LIST";
export const FETCH_SUBSCRIBERS_LIST_SUCCESS = "subscriberes/FETCH_SUBSCRIBERS_LIST_SUCCESS";
export const FETCH_SUBSCRIBERS_LIST_FAILURE = "subscriberes/FETCH_SUBSCRIBERS_LIST_FAILURE";